spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/onlin_post?currentSchema=test'
    username: postgres
    password: oybek
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update



admins:
  username: your_username
  password: your_password
  email: your_email